sudo: false
dist: trusty
language: java

matrix:
  include:
    - jdk: openjdk-ea
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: oraclejdk-ea
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: oraclejdk10
    - jdk: oraclejdk11

  
script: 
#  - "mvn cobertura:cobertura"
  - "mvn test -B"
  - "mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=c4394ad3c81d462380472c50c03f805c7eca9f0b"
  - "mvn org.pitest:pitest-maven:mutationCoverage"

after_success:
  - bash <(curl -s https://codecov.io/bash)
